### ISSUE TITLE
Request: allow moving to invalid location if current location is invalid

### ISSUE THREAD

**Issue by sparr** [Nexela/PickerDollies#13]
A rail signal or station can't be moved if there's no rail at the target location. This is moderately sensible. However, if there's no rail at the current location either then I think the user should be able to move it around freely. This should perhaps apply to any entities that have some placement validity check other than collision. On second thought, if an entity is already violating collision then I think it should be allowed to be moved to a new collision violating location, so this request applies to basically any reason an entity couldn't be moved to its current and new locations.

**Comment by Nexela** [comment]
I think this might be doable if you are up for testing an experimental build

**Comment by Nexela** [comment]
Pushed a commit that should mostly address this issue.

**Comment by sparr** [comment]
Since this issue was filed it has become possible to move train stations regardless of whether the new or old locations have rails to connect to.
