### ISSUE TITLE
New update breaks compatibility with Logistic Train Networks

### ISSUE THREAD

**Issue by steelstiletto** [Nexela/PickerDollies#15]
Installing just Picker Dollies and Logistic Train Networks and their dependencies causes a non-recoverable crash when starting a new game. This did not happen with the previous version, 1.1.7. 

The error from the game is:

-----------------------------
The mod LTN - Logistic Train Network (1.16.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LogisticTrainNetwork::on_init()
Error when running interface function PickerDollies.add_blacklist_name: __PickerDollies__/interface.lua:68: attempt to index field 'blacklist_names' (a nil value)
stack traceback:
	__PickerDollies__/interface.lua:68: in function <__PickerDollies__/interface.lua:65>
stack traceback:
	[C]: in function 'call'
	__LogisticTrainNetwork__/script/init.lua:286: in function 'registerEvents'
	__LogisticTrainNetwork__/script/init.lua:308: in function <__LogisticTrainNetwork__/script/init.lua:298>
--------------------------------

**Comment by Nexela** [comment]
Should be fixed-ish, I added a workaround however Mods using the add/remove api should add PickerDollies as an optional dependency
