### ISSUE TITLE
[1.0.2]: Inconsistent behavior with blacklisted entities

### ISSUE THREAD

**Issue by 0ptera** [Nexela/PickerDollies#3]
Entities like rails fail with a console message.

Entities blacklisted by remote calls fail silently.
When a valid entity had been moved prior, it will continue to move that entity.

**Comment by Nexela** [comment]
Well I moved all messages to the local flying text, added the missing messages.......ANDDDD somehow broke the blacklisting logic and I can't understand why because it is super simple........
NVM Must be tired.......... silly mistake Very silly

**Comment by Nexela** [comment]
Also not sure what you mean by a valid entity moved prior will continue to move?  The last entity moved is saved for 5 seconds. I might add an option to turn that off though

**Comment by 0ptera** [comment]
> 
> 
> Also not sure what you mean by a valid entity moved prior will continue to move? The last entity moved is saved for 5 seconds. I might add an option to turn that off though

This undocumented? feature is probably the reason for the percieved inconsitentcy.
Hovering over another movable entity sets that as to be moved, hovering over a blacklisted one retains the last moved entity.

For consistency hovering over a different entity should clear the cache regardless of what entity is highlighted.
